/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CustomerdeatilsImport } from './routes/customerdeatils'
import { Route as CartImport } from './routes/cart'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CustomerdeatilsRoute = CustomerdeatilsImport.update({
  id: '/customerdeatils',
  path: '/customerdeatils',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/customerdeatils': {
      id: '/customerdeatils'
      path: '/customerdeatils'
      fullPath: '/customerdeatils'
      preLoaderRoute: typeof CustomerdeatilsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/customerdeatils': typeof CustomerdeatilsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/customerdeatils': typeof CustomerdeatilsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/customerdeatils': typeof CustomerdeatilsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cart' | '/customerdeatils'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/customerdeatils'
  id: '__root__' | '/' | '/cart' | '/customerdeatils'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CustomerdeatilsRoute: typeof CustomerdeatilsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CustomerdeatilsRoute: CustomerdeatilsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/cart",
        "/customerdeatils"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/cart": {
      "filePath": "cart.jsx"
    },
    "/customerdeatils": {
      "filePath": "customerdeatils.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
