/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SuccessImport } from './routes/success'
import { Route as CustomerdeatilsImport } from './routes/customerdeatils'
import { Route as CartImport } from './routes/cart'
import { Route as CancelImport } from './routes/cancel'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SuccessRoute = SuccessImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRoute,
} as any)

const CustomerdeatilsRoute = CustomerdeatilsImport.update({
  id: '/customerdeatils',
  path: '/customerdeatils',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const CancelRoute = CancelImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/customerdeatils': {
      id: '/customerdeatils'
      path: '/customerdeatils'
      fullPath: '/customerdeatils'
      preLoaderRoute: typeof CustomerdeatilsImport
      parentRoute: typeof rootRoute
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/cart': typeof CartRoute
  '/customerdeatils': typeof CustomerdeatilsRoute
  '/success': typeof SuccessRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/cart': typeof CartRoute
  '/customerdeatils': typeof CustomerdeatilsRoute
  '/success': typeof SuccessRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/cart': typeof CartRoute
  '/customerdeatils': typeof CustomerdeatilsRoute
  '/success': typeof SuccessRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cancel' | '/cart' | '/customerdeatils' | '/success'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cancel' | '/cart' | '/customerdeatils' | '/success'
  id: '__root__' | '/' | '/cancel' | '/cart' | '/customerdeatils' | '/success'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancelRoute: typeof CancelRoute
  CartRoute: typeof CartRoute
  CustomerdeatilsRoute: typeof CustomerdeatilsRoute
  SuccessRoute: typeof SuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancelRoute: CancelRoute,
  CartRoute: CartRoute,
  CustomerdeatilsRoute: CustomerdeatilsRoute,
  SuccessRoute: SuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/cancel",
        "/cart",
        "/customerdeatils",
        "/success"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/cancel": {
      "filePath": "cancel.jsx"
    },
    "/cart": {
      "filePath": "cart.jsx"
    },
    "/customerdeatils": {
      "filePath": "customerdeatils.jsx"
    },
    "/success": {
      "filePath": "success.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
